language: python
python:
- '3.5'
build:
- make build
script:
- make test
- pip install codacy-coverage && python-codacy-coverage -r coverage.xml
deploy:
  provider: pypi
  user: justinbarrick
  password:
    secure: QRrwoiOfS1Jw8S4X2XzTy1Cm42lXWTX8Q3hKhrtjZ7qAjiQk6SiCG8ltA0KsTzHLnUPyr69ZuPM2Y1jCFzqVWp+re82e86LCFOYIQbLeWBIKc5y1717iRCqQcEnsO+gsP4SvrTR2Go/h02jopaxN7vGciF5I6SIlriO4NIM7hEygRhlVwSowqBW33ugXE6V6Pj5SHaMx2YLnQfNaiQFGDatSKtZxL4/57Q91uPE92y2vz3f8JE8PRsMsiP2Q+3F3o94jpMXZgczaRhVW0U9p2NB0UOXUjKkNrhqZ4THcNYw70uq8BSfmUTehkSfYw18HMQIndE677usIJAJlybLvZV+WghI/HXUzwSCfgVUicThdcXlk/teBolFBJYy3hj1yOj3MqATd5PxM2DkwrU9tdGmd/dBplQwgbdmHa0zvjWH0w5BGnsa3OgKkxmNvpZDN8DzleoKPWniBKSfWEZCRlbzBxqrobqOP+ZBZe24XyLF/2Ach/cBndWqAfI58KFdb06VgsnZHegDq6jisfv4yrhWFsR7cUWeLIlZoUIx4K9xYQevUgwvvV4wmKPWKmlJ2wyFdtOnA21wYIJt/DoTZuo7L3dhAKvoXYp5ZjEPEIZUz+ST2lOK/33NkFeWfBxT5hrsQfF4j1xl2/9uxzwaqyhJSXzKxRyKtB/5o+7YSDSU=
  on:
    branch: master
    tags: true
