language: python
python:
- '3.5'
build:
- make build
script:
- make test
- pip install codacy-coverage && python-codacy-coverage -r coverage.xml
deploy:
  provider: pypi
  user: justinbarrick
  password:
    secure: QRrwoiOfS1Jw8S4X2XzTy1Cm42lXWTX8Q3hKhrtjZ7qAjiQk6SiCG8ltA0KsTzHLnUPyr69ZuPM2Y1jCFzqVWp+re82e86LCFOYIQbLeWBIKc5y1717iRCqQcEnsO+gsP4SvrTR2Go/h02jopaxN7vGciF5I6SIlriO4NIM7hEygRhlVwSowqBW33ugXE6V6Pj5SHaMx2YLnQfNaiQFGDatSKtZxL4/57Q91uPE92y2vz3f8JE8PRsMsiP2Q+3F3o94jpMXZgczaRhVW0U9p2NB0UOXUjKkNrhqZ4THcNYw70uq8BSfmUTehkSfYw18HMQIndE677usIJAJlybLvZV+WghI/HXUzwSCfgVUicThdcXlk/teBolFBJYy3hj1yOj3MqATd5PxM2DkwrU9tdGmd/dBplQwgbdmHa0zvjWH0w5BGnsa3OgKkxmNvpZDN8DzleoKPWniBKSfWEZCRlbzBxqrobqOP+ZBZe24XyLF/2Ach/cBndWqAfI58KFdb06VgsnZHegDq6jisfv4yrhWFsR7cUWeLIlZoUIx4K9xYQevUgwvvV4wmKPWKmlJ2wyFdtOnA21wYIJt/DoTZuo7L3dhAKvoXYp5ZjEPEIZUz+ST2lOK/33NkFeWfBxT5hrsQfF4j1xl2/9uxzwaqyhJSXzKxRyKtB/5o+7YSDSU=
  on:
    branch: master
    tags: true
env:
  global:
    secure: EE4ciC+XtLiWCdB/RBmX/h8a1q3ptXVu8L5q9t3MEv0kqfsZ8qLTjoWI3Ub7SPeA2+vkp+Hdg+E3xrKAM81G2naeBPi8R0eT737fli5g+4Fqn8PFwDYT8AstoFBYOZQ3DYXUUTwhSBQq4mKZLKOHY/748jbtV/t0nrKzkDLZsWa9eASIjj6vjjecqTiVvTusZ89rcxIjtMDrNbvfNoxHSa90acFLfRtOUzLVt0kMorByN/zVc15DV8qY7n0Bx27BagPiGZUwWBxXUrYgM1DoCY/HMeZvk8SU6GxBA4dbecygYhHvX7yQK8dFdvAWm7Zb+2UBEML4OpbDjttXtlQbjIVdF1WveC7C+HfwZmbmwTvIm7FFIFf4cZGC+/kaUNKeIqvlQdSdxvNAsOz8p/h1YsPWv8ITK2IypPEDaVVRyqh0Y4nUCBQ1P9AMc5Z4r85oVP4PFnkwyq5PaHRnyu6TYcu/Mo+QbQrqBlOspBz7BITdXzb13m2Qskrch7E5r9hAgptj8MaGHZzR1W1tsOqjzsiwjweG2RXGIVQ6uWjuso1a9SdzSVq4f00aFylPDa5vYzC5A2Cs12DxJCRma3pbTUwBSun9nM/joW4K4hX1xsMmjpWSCKwhoRtArSjgzy+E4RFSIaSBTFO9JRwvI5yr/zSmKtvtUuQor7oaRYn6tz4=
